env:
  browser: true
  es2020: true
  node: true
extends:
  - eslint:recommended
  - plugin:react/recommended
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
  sourceType: module
plugins:
  - react
  - react-hooks
rules:
  semi: [error, never]
  react/prop-types: 'off'
  no-console: [error, allow: [warn, error]]
  react-hooks/rules-of-hooks: error
  react-hooks/exhaustive-deps: warn
settings:
  react:
    version: detect
